
_meta.script_name: parse-col-actions


graph-path: extra/col/adj/graph.yaml
players-path: extra/col/adj/players.yaml

alias-path: extra/col/adj/aliases.yaml

#log-path: extra/col/adj/game/raw/1-1.txt
#action-path: extra/col/adj/game/actions/1-1.yaml
#state-path: extra/col/adj/game/states/1-1.yaml

parser:
  _type: parser
  term-filter: [player]
