

manager.renderer._type: wd-hills-rendering

highlight-size: 1.8
highlight-width: 0.3

unit-size: 1.2
unit-bg-size: 1.5
unit-edge-width: 0.24
#unit-padding: 0.2

unit-delta: [-0.5, 1.5]

sc-size: 0.7
capital-size: 1.5
sc-edge-width: 0.08
sc-color: '#EFE4B0'
sc-dot-size: 0.16

sc-dot-props:
  ms: <>sc-dot-size
  color: k
#  marker: s
#  marker: ","
  marker: o
  ls: ''
  zorder: 64
home-props:
  markeredgewidth: <>sc-edge-width
  markeredgecolor: k
  markersize: <>sc-size
  marker: s
  ls: ''
  zorder: 62
sc-props:
  markeredgewidth: <>sc-edge-width
  markerfacecolor: <>sc-color
  markeredgecolor: k
  markersize: <>sc-size
  marker: s
  ls: ''
  zorder: 61
capital-props:
  markersize: <>capital-size
#  markeredgewidth: <>sc-edge-width
  markeredgecolor: k
  markerfacecolor: k
#  color: k
#  marker: P
  marker: +
  mew: 0.4
  ls: ''
  zorder: 60


label-size: 4
coast-label-size: 3.5
label-padding: 0.4

unit-props:
  size: <>unit-size
  weight: heavy
  va: center
  ha: center
#  bbox:
##    facecolor: w
##    edgecolor: k
#    facecolor: none
#    edgecolor: k
#    lw: <>unit-edge-width
##    pad: <>unit-padding
#    boxstyle: square,pad=0.1
  zorder: 21
unit-bg:
  ms: <>unit-bg-size
  marker: s
  mew: <>unit-edge-width
  mec: k
  zorder: 20


arrow-ratio: 0.9
arrow-width: 3
arrow-head: 8
edge-width: 0.2


hold-color: <>sup-color
sup-color: y
convoy-color: c
edge-color: k

wedge-dot-size: 0.64

support-style: wedge,tail_width=0.05,shrink_factor=0.5
support-shrink: 0

support-defend-style: wedge,tail_width=0.075,shrink_factor=0.5
support-defend-shrink: 0.2

convoy-style: wedge,tail_width=0.05,shrink_factor=0.5
convoy-shrink: 0

retreat-arrow:
  width: <>arrow-width
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  fc: r
  ec: k
  zorder: 19
retreat-action-arrow: <>retreat-arrow
retreat-props:
  ms: <>highlight-size
  mew: <>highlight-width
  mec: r
  mfc: None
  zorder: 50
  ls: ''
  marker: o
disband-props:
  ms: <>highlight-size
  mew: <>highlight-width
  mec: r
  mfc: None
  zorder: 50
  ls: ''
  marker: x


core-props:
  ms: <>highlight-size
  mew: <>highlight-width
  mec: '#964b00'
  mfc: None
  zorder: 50
  ls: ''
  marker: D # d


hold-props:
  color: <>hold-color
  ms: <>highlight-size
  mew: <>highlight-width
  ls: ''
  mfc: 'none'
  marker: s
  zorder: 21
build-props:
  color: '#00ff00'
  ms: <>highlight-size
  mew: <>highlight-width
  ls: ''
  marker: s
#  mfc: 'none'
  zorder: 6

move-arrow:
  width: <>arrow-width
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  facecolor: w
  edgecolor: k
  zorder: 15

support-arrow:
  width: <>arrow-width
  ls: --
  fc: <>sup-color
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  facecolor: <>sup-color
  edgecolor: <>edge-color
  zorder: 6
support-props:
  arrowprops:
    shrinkA: <>support-shrink
    shrinkB: <>support-shrink
    arrowstyle: <>support-style
    capstyle: round
    linewidth: <>edge-width
    facecolor: <>sup-color
    edgecolor: <>edge-color
    connectionstyle: arc3,rad=0.2

  zorder: 7
support-dot:
  marker: o
  ms: <>wedge-dot-size
#  lw: 1
  mew: <>edge-width
  ls: ''
  color: <>sup-color
  mec: <>edge-color
  zorder: 16

support-defend-props:
  textcoords: data
  xycoords: data
  arrowprops:
    shrinkA: <>support-defend-shrink
    shrinkB: <>support-defend-shrink
    arrowstyle: <>support-defend-style
    capstyle: round
    linewidth: <>edge-width
    facecolor: <>sup-color
    edgecolor: <>edge-color
    connectionstyle: arc3,rad=0.2

  zorder: 6

convoy-dot:
  marker: o
  ms: <>wedge-dot-size
#  lw: 1
  mew: <>edge-width
  ls: ''
  color: <>convoy-color
  mec: <>edge-color
  zorder: 16



