

manager.renderer._type: classic-renderer


#year_offset: 1900
year_props:
  x: 30
  y: 100
  ha: left
  va: bottom
  fontsize: 9
  fontfamily: monospace
  zorder: 50
  color: w

season_titles:
  1: SPRING
  2: FALL
  3: WINTER
season_props:
  x: 170
  y: 100
  ha: left
  va: bottom
  fontsize: 9
  fontfamily: monospace
  zorder: 50
  color: w

highlight_size: 8
highlight_width: 1

sc_size: 5
capital_size: 5.5
home_size: 1.5
sc_edge_width: 0.2
home_edge_width: 0.1

unit_size: 6
unit_edge_width: 1.2

arrow_ratio: 0.9
arrow_width: 8
arrow_head: 24
edge_width: 0.45


hold_color: <>sup_color
sup_color: y
convoy_color: c
edge_color: k

wedge_dot_size: 2.5

support_style: wedge,tail_width=0.15,shrink_factor=0.5
support_shrink: 0.05

support_defend_style: wedge,tail_width=0.20,shrink_factor=0.5
support_defend_shrink: 0.2

convoy_style: wedge,tail_width=0.15,shrink_factor=0.5
convoy_shrink: 0

label_size: 4
coast_label_size: 3.5
label_padding: 0.4

label_props:
  size: <>label_size
  weight: normal
  va: center
  ha: center
  bbox:
#    facecolor: w
#    edgecolor: k
    facecolor: none
    edgecolor: none
    lw: 0.4
    pad: <>label_padding
  zorder: 3
coast_label_props:
  size: <>coast_label_size
  weight: normal
  va: center
  ha: center
  bbox:
#    facecolor: w
#    edgecolor: k
    facecolor: none
    edgecolor: none
    lw: 0.4
    pad: <>label_padding
  zorder: 3

sc_props:
  markersize: <>sc_size
  markeredgewidth: <>sc_edge_width

  markeredgecolor: k
  markerfacecolor: '#FFD700'
  marker: [5,1]
  ls: ''
  zorder: 4
capital_props:
  markersize: <>capital_size
  markeredgewidth: <>sc_edge_width
  markeredgecolor: k
  markerfacecolor: '#FFD700'
#  marker: [7, 1]
  marker: [5, 1]
  ls: ''
  zorder: 4
home_props:
  markeredgewidth: <>home_edge_width
  markeredgecolor: k
  markersize: <>home_size
  marker: o
  ls: ''
  zorder: 5

unit_props:
  ms: <>unit_size
  mew: <>unit_edge_width
  zorder: 20
  mec: k
  ls: ''

retreat_arrow:
  width: <>arrow_width
  lw: <>edge_width
  head_width: <>arrow_head
  length_includes_head: True
  fc: r
  ec: k
#  zorder: 19
  zorder: 45
retreat_action_arrow: <>retreat_arrow
retreat_props:
  ms: <>highlight_size
  mew: <>highlight_width
  mec: r
  mfc: None
  zorder: 50
  ls: ''
  marker: o
disband_props:
  ms: <>highlight_size
  mew: <>highlight_width
  mec: r
  mfc: None
  zorder: 50
  ls: ''
  marker: x

hold_props:
  color: <>hold_color
  ms: <>highlight_size
  mew: <>highlight_width
  ls: ''
  mfc: 'none'
#  zorder: 21
  zorder: 25
build_props:
  color: '#00ff00'
  ms: <>highlight_size
  mew: <>highlight_width
  ls: ''
#  mfc: 'none'
#  zorder: 6
  zorder: 50

move_arrow:
  width: <>arrow_width
  lw: <>edge_width
  head_width: <>arrow_head
  length_includes_head: True
  facecolor: w
  edgecolor: k
#  zorder: 15
  zorder: 40


support_arrow:
  width: <>arrow_width
  ls: --
  fc: <>sup_color
  lw: <>edge_width
  head_width: <>arrow_head
  length_includes_head: True
  facecolor: <>sup_color
  edgecolor: <>edge_color
#  zorder: 6
  zorder: 25
support_props:
  arrowprops:
#    shrinkA: <>support_shrink
    shrinkA: 0
    shrinkB: <>support_shrink
    arrowstyle: <>support_style
    capstyle: round
    linewidth: <>edge_width
    facecolor: <>sup_color
    edgecolor: <>edge_color
    connectionstyle: arc3,rad=0.2

#  zorder: 7
  zorder: 26
support_dot:
  marker: o
  ms: <>wedge_dot_size
#  lw: 1
  mew: <>edge_width
  ls: ''
  color: <>sup_color
  mec: <>edge_color
#  zorder: 16
  zorder: 41

support_defend_props:
  textcoords: data
  xycoords: data
  arrowprops:
#    shrinkA: <>support_defend_shrink
    shrinkA: 0
    shrinkB: <>support_defend_shrink
    arrowstyle: <>support_defend_style
    capstyle: round
    linewidth: <>edge_width
    facecolor: <>sup_color
    edgecolor: <>edge_color
    connectionstyle: arc3,rad=0.2

#  zorder: 6
  zorder: 28


convoy_arrow:
  width: <>arrow_width
  ls: --
  fc: <>convoy_color
  lw: <>edge_width
  head_width: <>arrow_head
  length_includes_head: True
  facecolor: <>convoy_color
  edgecolor: <>edge_color
#  zorder: 6
  zorder: 30
convoy_props:
  arrowprops:
#    shrinkA: <>convoy_shrink
    shrinkA: 0
    shrinkB: <>convoy_shrink
    arrowstyle: <>convoy_style
    capstyle: round
    linewidth: <>edge_width
    facecolor: <>convoy_color
    edgecolor: <>edge_color
    connectionstyle: arc3,rad=0.2

#  zorder: 7
  zorder: 31
convoy_dot:
  marker: o
  ms: <>wedge_dot_size
#  lw: 1
  mew: <>edge_width
  ls: ''
  color: <>convoy_color
  mec: <>edge_color
#  zorder: 16
  zorder: 42


