

manager.renderer._type: default-renderer

highlight-size: 8
highlight-width: 1

sc-size: 5
capital-size: 5.5
home-size: 1.5
sc-edge-width: 0.2
home-edge-width: 0.1

unit-size: 6
unit-edge-width: 1.5

arrow-ratio: 0.9
arrow-width: 10
arrow-head: 24
edge-width: 0.45


hold-color: <>sup-color
sup-color: y
convoy-color: c
edge-color: k

wedge-dot-size: 2.5

support-style: wedge,tail_width=0.2,shrink_factor=0.5
support-shrink: 0

support-defend-style: wedge,tail_width=0.3,shrink_factor=0.5
support-defend-shrink: 0.1

convoy-style: wedge,tail_width=0.2,shrink_factor=0.5
convoy-shrink: 0

label-size: 4
coast-label-size: 3.5
label-padding: 0.4

label-props:
  size: <>label-size
  weight: normal
  va: center
  ha: center
  bbox:
#    facecolor: w
#    edgecolor: k
    facecolor: none
    edgecolor: none
    lw: 0.4
    pad: <>label-padding
  zorder: 3
coast-label-props:
  size: <>coast-label-size
  weight: normal
  va: center
  ha: center
  bbox:
#    facecolor: w
#    edgecolor: k
    facecolor: none
    edgecolor: none
    lw: 0.4
    pad: <>label-padding
  zorder: 3

sc-props:
  markersize: <>sc-size
  markeredgewidth: <>sc-edge-width

  markeredgecolor: k
  markerfacecolor: '#FFD700'
  marker: [5,1]
  ls: ''
  zorder: 60
capital-props:
  markersize: <>capital-size
  markeredgewidth: <>sc-edge-width
  markeredgecolor: k
  markerfacecolor: '#FFD700'
  marker: [7, 1]
  ls: ''
  zorder: 60
home-props:
  markeredgewidth: <>home-edge-width
  markeredgecolor: k
  markersize: <>home-size
  marker: o
  ls: ''
  zorder: 61

unit-props:
  ms: <>unit-size
  mew: <>unit-edge-width
  zorder: 20
  mec: k
  ls: ''

retreat-arrow:
  width: <>arrow-width
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  fc: r
  ec: k
  zorder: 19
retreat-action-arrow: <>retreat-arrow
retreat-props:
  ms: <>highlight-size
  mew: <>highlight-width
  mec: r
  mfc: None
  zorder: 50
  ls: ''
  marker: o
disband-props:
  ms: <>highlight-size
  mew: <>highlight-width
  mec: r
  mfc: None
  zorder: 50
  ls: ''
  marker: x

hold-props:
  color: <>hold-color
  ms: <>highlight-size
  mew: <>highlight-width
  ls: ''
  mfc: 'none'
  zorder: 21
build-props:
  color: '#00ff00'
  ms: <>highlight-size
  mew: <>highlight-width
  ls: ''
#  mfc: 'none'
  zorder: 6

move-arrow:
  width: <>arrow-width
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  facecolor: w
  edgecolor: k
  zorder: 15


support-arrow:
  width: <>arrow-width
  ls: --
  fc: <>sup-color
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  facecolor: <>sup-color
  edgecolor: <>edge-color
  zorder: 6
support-props:
  arrowprops:
    shrinkA: <>support-shrink
    shrinkB: <>support-shrink
    arrowstyle: <>support-style
    capstyle: round
    linewidth: <>edge-width
    facecolor: <>sup-color
    edgecolor: <>edge-color
    connectionstyle: arc3,rad=0.2

  zorder: 7
support-dot:
  marker: o
  ms: <>wedge-dot-size
#  lw: 1
  mew: <>edge-width
  ls: ''
  color: <>sup-color
  mec: <>edge-color
  zorder: 16

support-defend-props:
  textcoords: data
  xycoords: data
  arrowprops:
    shrinkA: <>support-defend-shrink
    shrinkB: <>support-defend-shrink
    arrowstyle: <>support-defend-style
    capstyle: round
    linewidth: <>edge-width
    facecolor: <>sup-color
    edgecolor: <>edge-color
    connectionstyle: arc3,rad=0.2

  zorder: 6


convoy-arrow:
  width: <>arrow-width
  ls: --
  fc: <>convoy-color
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  facecolor: <>convoy-color
  edgecolor: <>edge-color
  zorder: 6
convoy-props:
  arrowprops:
    shrinkA: <>convoy-shrink
    shrinkB: <>convoy-shrink
    arrowstyle: <>convoy-style
    capstyle: round
    linewidth: <>edge-width
    facecolor: <>convoy-color
    edgecolor: <>edge-color
    connectionstyle: arc3,rad=0.2

  zorder: 7
convoy-dot:
  marker: o
  ms: <>wedge-dot-size
#  lw: 1
  mew: <>edge-width
  ls: ''
  color: <>convoy-color
  mec: <>edge-color
  zorder: 16


