
_meta.script_name: start-bot
#
#server-name: playground
#
##admins: None
#admin_role: Host
#server_name: Digi-Diplo

admin_role: testhost
server_name: playground
#
######################
#
##_meta.script_name: multi-step
##_meta.script_name: step
##_meta.script_name: render
#
#_base: [ad/std]
##_base: [wd/style, wd/bot]
#_base: [wd/hills, wd/bot]
##_base: [wd/std]
_base: [classic/bot]
##_base: [classic/bot]
#_base: [balkans/bot]

game-root: games/ada2
#game-root: games/game12

reverse_coords: yes


#_base: [ad/std]
#game-root: games/game15


################################

#_meta.script_name: tile-img
#fig tile-img --root C:\Users\anwan\OneDrive\Khan\projects\digi-diplo\extra\v3\example --rgb-path base.png

#_meta.script_name: link-tiles
#fig link-tiles --root C:\Users\anwan\OneDrive\Khan\projects\digi-diplo\extra\v3\example --rgb-path base.png --dot-path cats.png

#root: "C:\\Users\\anwan\\OneDrive\\Khan\\projects\\digi-diplo\\extra\\v3\\example"

#_meta.script_name: view-labels
#fig view-labels --root C:\Users\anwan\OneDrive\Khan\projects\digi-diplo\extra\v3\world --rgb-path renderbase.png --label-path tiles.png

#_meta.script_name: link-names
#fig link-names --root C:\Users\anwan\OneDrive\Khan\projects\digi-diplo\extra\v3\example --names-path names.txt

#_meta.script_name: extract-graph
#fig extract-graph --root C:\Users\anwan\OneDrive\Khan\projects\digi-diplo\extra\v3\example


#_meta.script_name: include-location
#fig include-location --root C:\Users\anwan\OneDrive\Khan\projects\digi-diplo\extra\v3\example --loc-name unit --loc-path unit_dots.png

#_meta.script_name: set-supply-centers
#fig set-supply-centers --root [...] --loc-path sc_dots.png

#_meta.script_name: check-graph
##fig check-graph --root [...] --auto-fix
#
##root: extra/v3/tests/
##rgb-path: borders.png
##dot-path: cats.png
#
##label-path: regions.png
##
##auto-fix: yes
#
#root: assets/ad/
##root: extra/v3/world/
##rgb-path: renderbase.png
###dot-path: dotz.png
##
###replace: yes
##
###loc-name: label
###loc-path: label.png
###loc-name: unit
###loc-path: units.png
###loc-name: retreat
###loc-path: retreats.png
###loc-name: coast-retreat
###loc-path: coast-retreats.png
###loc-name: coast-unit
###loc-path: coasts.png


####################







#label-path: regions.png

#start: 59

#start: 100

#dot-path: cats.png
#categories:
#  '#00ff21': land
#  '#00ffff': sea


#manager:
#  _type: diplo-manager
#
#  map:
#    _type: diplo-map
#    _mod.dash-coasts: 1


#game-root: games/game4
#game-root: games/bravo
#game-root: games/charlie
#game-root: examples/game213263

#check-image: 1-1
#current: 2-2

#allow-missing: 2
#include-orders: yes
#render-orders: yes
#render-state: yes

#log-commands: yes
#private-commands: yes

#view: yes
#pbar: true
#skip-control: true

#disband-props.zorder: 5000

#manager.renderer._mod.wd-unit-arrows: 1

#  retreat:
#    marker: o
#  disband:
#    marker: x

#admins: [felixludos#9043]

#_base: [automap/viz]
##
##state-path: extra/game/states/8-1-r.yaml
##save-path: extra/game/images/8-1-r.png
#
#state-path: extra/game/states/8-2.yaml
#action-path: extra/game/actions/8-2.yaml
#save-path: extra/game/images/8-2_actions_new.png

#fill-units: True
#skip-filling: True
#skip-bgs: True
#skip-labeling: True

#---------------------

#_base: [automap/new]

#_meta.script_name: diplo-new
#
#save-root: extra/game/states

#---------------------

#_base: [automap/parse]
#
#log-path: extra/game/raw/8-1-r.txt
#action-path: extra/game/actions/parsed/8-1-r.yaml


#---------------------

#_base: [automap/step]
#
#state-path: extra/game/states/8-1.yaml
#action-path: extra/game/actions/8-1.yaml



#---------------------



#_base: [automap/scs]


#_meta.script_name: map-identities
#_meta.script_name: view-idents
#_meta.script_name: match-names
#_meta.script_name: categorize-fields
#_meta.script_name: edge-finder

#_meta.script_name: viz-map
#
#save-path: extra/col/test-viz.png
#nodes-path: extra/col/nodes.yaml
#path: extra/col/full.yaml
#
#img-path: extra/col/col_fixed_v2.gif
#fields-img: extra/col/col_fixed_v2_nodes.png
#
#names-path: extra/col/col_names.txt
#data-path: extra/col/col_idents_v2.yaml
#
#fix-diagonals: False
#
#color-map:
#  land: [ 44, 160, 44 ] #2ca02c
#  sea: [ 31, 119, 180 ] #1f77b4
#  lake: [ 23, 190, 207 ] #17becf
#  island: [ 255, 127, 14 ] #ff7f0e
#  background: [ 0,0,0 ]
#  river: [ 23, 190, 207 ] #17becf
#  mountains: [ 140, 86, 75 ] #8c564b
#  desert: [ 188, 189, 34 ] #bcbd22
#  background-island: [ 127, 127, 127 ] #7f7f7f
#  ocean: [ 31, 119, 180 ] #1f77b4
#
#text-props:
##  backgroundcolor: w
#  ha: center
#  va: center
#  fontsize: 0.5
#  bbox:
#    pad: 0.05
#    ec: k
#    fc: w
#    lw: 0.05
#    alpha: 0.8
#
#
#categories:
#  0: land
#  1: sea
#  2: lake
#  3: island
#  4: background
#  5: river
#  6: mountains
#  7: desert
#  8: background-island
#  9: ocean
#
#cat-decoder:
#  land: land
#  sea: sea
#  coast: coast
#  island: coast
#  desert: land
#  ocean: sea
#
#cat-colors:
#  0: [44, 160, 44] #2ca02c
#  1: [31, 119, 180] #1f77b4
#  2: [23, 190, 207] #17becf
#  3: [255, 127, 14] #ff7f0e
#  4: [127, 127, 127] #7f7f7f
#  5: [23, 190, 207] #17becf
#  6: [140, 86, 75] #8c564b
#  7: [188, 189, 34] #bcbd22
#  8: [ 127, 127, 127 ] #7f7f7f
#  9: [ 31, 119, 180 ] #1f77b4
#
#skip-coasts:
#  - Gothenburg
#  - Denmark
#  - Noquet
#  - Caucasus
#  - Sault Ste. Marie
#  - Athens
#  - Konstaniniyye
#  - Hiroshima
#  - Eskenderiyya
#  - Panama
##  - Sevilla
#
#multi-nodes:
#  NAO: [NAO1, NAO2, NAO3, NAO4, NAO5]
#  PAO: [PAO1, PAO2, PAO3, PAO4, PAO5]
#  SAO: [SAO1, SAO2, SAO3, SAO4, SAO5]
#  INO: [INO1, INO2, INO3, INO4, INO5]
#  ANT: [ANT1, ANT2, ANT3, ANT4, ANT5]
#  WSA: [WSA1, WSA2, WSA3]
#  ESA: [ESA1, ESA2, ESA3]
#
#split-nodes:
#  - Beaufort Sea
#  - Bering Strait
#  - Northeast Pacific Ocean
#  - PAO
#  - PAO1
#  - PAO2
#  - PAO3
#  - PAO4
#  - PAO5
#  - Tuamotu Archipelago
#  - Southwest Pacific Ocean

#field: 905

# old ------------------------


##_meta.script_name: collect-pos
##_meta.script_name: node-locs
##_meta.script_name: mapping
#_meta.script_name: diplo-step
#
##_meta.script_name: parse-vdip
#
##_base: ["test/node-locs"]
##_base: ["test/mapping"]
##_base: ["test/collect-pos"]
##_base: ["test/collect-fills"]
#
#
##_base: [test/render_state]
##_base: [test/render_traj]
##_base: [test/traj]
##_base: [test/take_step]
##_base: [test/new_game]
##_base: [test/parse_vdip]
##_base: [test/collect-pos]
##_base: [test/fills]
#
#_base: [colors/vdip, viz/classic]
#
#state-path: extra\mygame1\states\7-1.yaml
#action-path: extra\mygame1\tentative.yaml
#
#render-state: True
#render-actions: True
#view: True
#
##log_path: extra\raw.txt
#
##_meta.script_name: new-diplo
#
##map:
##  _type: map
#
##root: C:\Users\anwan\Nextcloud\Khan\projects\ludos\examples\diplomacy
#
##image_path: extra\vanilla_blank.gif
##edges_path: data\base_edges.yaml
#
##name: test
##
##image_path: extra\standard_c.gif
##nodes_path: test_nodes.yaml
##edges_path: test_edges.yaml
#
##pos_path: <>out_path
#
##out_path: data\base_pos.yaml
#
#
##base: False
##text: False
##retreat: False



