
parents: [colors/classic]

image-path: extra\standard_c_simple.gif

map:
  _type: map
  root: data\classic

scale: 1.6

title:
  color: w
  size: 20
  x: 10
  y: 30
  year: 1900
  font: monospace
  weight: normal

#font-weight: bold
clear-bg: True
clear-edge: True

marker.size: 12
marker.edge: 3
retreat:
  style: "o"
  disband: "x"
  size: 16
  color: 'r'
  edge: 1.5

view: True

font:
  size: 6

color: w
hold.color: w
support.color: y
support.def-color: y

build.color: "#00FF00"
convoy.color: c
#convoy.include-move: True

support.ratio: 0.95

arrow:
  width: 6
  head-width: 24
  ratio: 0.85
  edge-color: k

text:
  pad: 2
  weight: normal
  clear-bg: True
  clear-edge: True

center:
  size: 10
  edge-width: 1
  marker: "*"


