

manager.renderer._type: wd-pixel-rendering

unit-zorder: 21
sc-zorder: 4

patterns:
  sc: [
        [0, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 1, 0],
        [0, 1, 0, 0, 1, 0],
        [0, 1, 0, 0, 1, 0],
        [0, 1, 1, 1, 1, 0],
        [0, 0, 0, 0, 0, 0]
    ]
  capital: [
        [1, 1, 1, 0, 0, 1, 1, 1],
        [1, 0, 0, 0, 0, 0, 0, 1],
        [1, 0, 1, 1, 1, 1, 0, 1],
        [0, 0, 1, 0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0, 1, 0, 0],
        [1, 0, 1, 1, 1, 1, 0, 1],
        [1, 0, 0, 0, 0, 0, 0, 1],
        [1, 1, 1, 0, 0, 1, 1, 1],
    ]

neutral-color: '#EFE4B0'

default-colors: ['#000000', <>neutral-color, null]

pattern-colors:
  sc: <>default-colors
  capital: <>default-colors
  fleet: <>default-colors
  army: <>default-colors





#arrow-hop: 0.02
arrow-ratio: 0.9
arrow-width: 3
arrow-head: 8
edge-width: 0.2


hold-color: <>sup-color
sup-color: y
convoy-color: c
edge-color: k

wedge-dot-size: 0.64

support-style: wedge,tail_width=0.05,shrink_factor=0.5
support-shrink: 0

support-defend-style: wedge,tail_width=0.075,shrink_factor=0.5
support-defend-shrink: 0.2

convoy-style: wedge,tail_width=0.05,shrink_factor=0.5
convoy-shrink: 0

retreat-arrow:
  width: <>arrow-width
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  fc: r
  ec: k
  zorder: 19
retreat-action-arrow: <>retreat-arrow
retreat-props:
  ms: <>highlight-size
  mew: <>highlight-width
  mec: r
  mfc: None
  zorder: 50
  ls: ''
  marker: <>highligh-marker
disband-props:
  ms: <>highlight-size
  mew: <>highlight-width
  mec: r
  mfc: None
  zorder: 50
  ls: ''
  marker: x


core-props:
  ms: <>highlight-size
  mew: <>highlight-width
  mec: '#964b00'
  mfc: None
  zorder: 50
  ls: ''
  marker: D # d


hold-props:
  color: <>hold-color
  ms: <>highlight-size
  mew: <>highlight-width
  ls: ''
  mfc: 'none'
  marker: <>highligh-marker
  zorder: 21
build-props:
  mec: '#00ff00'
  mfc: None
  ms: <>highlight-size
  mew: <>highlight-width
  ls: ''
  marker: <>highligh-marker
#  mfc: 'none'
  zorder: 6

move-arrow:
  width: <>arrow-width
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  facecolor: w
  edgecolor: k
  zorder: 15

support-arrow:
  width: <>arrow-width
  ls: --
  fc: <>sup-color
  lw: <>edge-width
  head_width: <>arrow-head
  length_includes_head: True
  facecolor: <>sup-color
  edgecolor: <>edge-color
  zorder: 6
support-props:
  arrowprops:
    shrinkA: <>support-shrink
    shrinkB: <>support-shrink
    arrowstyle: <>support-style
    capstyle: round
    linewidth: <>edge-width
    facecolor: <>sup-color
    edgecolor: <>edge-color
    connectionstyle: arc3,rad=0.2

  zorder: 7
support-dot:
  marker: o
  ms: <>wedge-dot-size
#  lw: 1
  mew: <>edge-width
  ls: ''
  color: <>sup-color
  mec: <>edge-color
  zorder: 16

support-defend-props:
  textcoords: data
  xycoords: data
  arrowprops:
    shrinkA: <>support-defend-shrink
    shrinkB: <>support-defend-shrink
    arrowstyle: <>support-defend-style
    capstyle: round
    linewidth: <>edge-width
    facecolor: <>sup-color
    edgecolor: <>edge-color
    connectionstyle: arc3,rad=0.2

  zorder: 6

convoy-dot:
  marker: o
  ms: <>wedge-dot-size
#  lw: 1
  mew: <>edge-width
  ls: ''
  color: <>convoy-color
  mec: <>edge-color
  zorder: 16

