
_meta.script_name: map-attribute

fields-img: extra/col/col_fixed_v2_nodes.png
path: extra/col/full.yaml

attr-key: sc

categories:
  1: 0
  2: 1

filters:
  type: [land, coast]

cat-colors:
  1: [ 127, 127, 127 ] #7f7f7f
  2: [255, 127, 14] #ff7f0e

