
_meta.script_name: viz-map

parents: [automap/col]

#save-path: extra/col/test-viz4.png

color-water: True

#skip-filling: True
#skip-bgs: True

#color-map:
#  land: [ 44, 160, 44 ] #2ca02c
#  sea: [ 31, 119, 180 ] #1f77b4
#  lake: [ 23, 190, 207 ] #17becf
#  island: [ 255, 127, 14 ] #ff7f0e
#  background: [ 0,0,0 ]
#  river: [ 23, 190, 207 ] #17becf
#  mountains: [ 140, 86, 75 ] #8c564b
#  desert: [ 188, 189, 34 ] #bcbd22
#  background-island: [ 127, 127, 127 ] #7f7f7f
#  ocean: [ 31, 119, 180 ] #1f77b4

color-map:
  land: '#FFFFFF'
  coast: '#FFFFFF'
  island: '#FFFFFF'
  desert: '#FFFFFF'

  sea: '#C2E2F6'
  lake: '#C2E2F6'

  river: '#C2E2F6'
  edge: '#000000'
  mountains: '#543210'
  bg-desert: '#E0E0E0'
  bg-island: <>bg-desert
  ocean: '#85C3EA'

text-props:
#  backgroundcolor: w
  ha: center
  va: center
  fontsize: 0.4
#  color: w
  color: w

  border:
    linewidth: 0.1
    foreground: k
#    linewidth: 0.03
#    facecolor: k
#    edgecolor: w

  zorder: 70

sc-props:
  markeredgewidth: 0.02
  markeredgecolor: k
  markerfacecolor: '#FFD700'
  markersize: 1
  marker: '*'
  ls: ''
  zorder: 60

capital-props:
  markeredgewidth: 0.02
  markeredgecolor: k
  markerfacecolor: '#FFD700'
  markersize: 1.2
  marker: [7, 1]
  ls: ''
  zorder: 60

home-props:
  markeredgewidth: 0.02
  markeredgecolor: k
  markersize: 0.32
  marker: o
  ls: ''
  zorder: 61

canal-props:
  color: c
  lw: 0.1
  zorder: 10

artist:
  _type: map-artist
  _mod: [canal]

action-props:
  _type: flatten-kwargs
  ms: 1.8
  mew: 0.3
  mec: r
  mfc: None
  zorder: 50
  ls: ''

  retreat:
    marker: o
  disband:
    marker: x

action-pos-aliases:
  disband: retreat

arrow-ratio: 0.9
retreat-arrow:

  width: 5
  lw: 0.1
  head_width: 12
  length_includes_head: True
  fc: r
  ec: k
  zorder: 19

move-arrow:
  width: 5
  lw: 0.1
  head_width: 12
  length_includes_head: True
  facecolor: w
  edgecolor: k
  zorder: 15

support-wedge:
  arrowprops:
#    width: 3
    arrowstyle: wedge
    capstyle: round
    linewidth: 0.1
    facecolor: y
    edgecolor: k
    connectionstyle: "arc3,rad=0.2"
    shrinkA: 0.2
    shrinkB: 0.2

  zorder: 12

support-arrow:
  width: 5
  ls: --
  lw: 0.1
  head_width: 12
  length_includes_head: True
  facecolor: y
  edgecolor: k
  zorder: 13

support-dot:
  marker: o
  ms: 0.8
  mew: 0.1
  color: y
  mec: k
  zorder: 18

transform-props:
  ms: 1.8
  mew: 0.3
  mec: m
  mfc: None
  zorder: 21
  ls: ''
  marker: '^'

unit-props:
  _type: flatten-kwargs

  ms: 1.5
  mew: 0.25
  zorder: 20
  mec: k
  ls: ''

  army:
    marker: o
  fleet:
    marker: v




